# LeadFlow Phase 1 folder creation reference.
# This script documents the intended scaffold and may be reused in clean environments.

$directories = @(
  "backend",
  "frontend",
  "docs",
  "prompts",
  "tests",
  "scripts",
  "legacy_crm",
  "backend/crm_core/models",
  "backend/crm_core/services",
  "backend/crm_core/repositories",
  "backend/lead_ingestion/meta",
  "backend/lead_ingestion/google",
  "backend/lead_ingestion/csv",
  "backend/lead_ingestion/website",
  "backend/lead_ingestion/manual",
  "backend/ai_engine/providers/nim",
  "backend/ai_engine/providers/gemini",
  "backend/ai_engine/providers/ollama",
  "backend/ai_engine/qualification",
  "backend/ai_engine/business_context",
  "backend/ai_engine/outreach_generation",
  "backend/ai_engine/reply_analysis",
  "backend/ai_engine/conversion_prediction",
  "backend/outreach/email",
  "backend/outreach/whatsapp",
  "backend/outreach/linkedin",
  "backend/outreach/scheduler",
  "backend/followups/rules",
  "backend/followups/scheduler",
  "backend/followups/automation",
  "backend/analytics/dashboard",
  "backend/analytics/conversion",
  "backend/analytics/engagement",
  "backend/analytics/forecasting",
  "backend/integrations/ai",
  "backend/integrations/resend",
  "backend/integrations/meta",
  "backend/integrations/google",
  "backend/integrations/webhooks",
  "backend/database/models",
  "backend/database/migrations",
  "backend/database/seeders",
  "backend/api",
  "backend/utils",
  "frontend/app/dashboard",
  "frontend/app/leads",
  "frontend/app/lead-details",
  "frontend/app/pipeline",
  "frontend/app/outreach",
  "frontend/app/followups",
  "frontend/app/analytics",
  "frontend/app/business-context",
  "frontend/app/settings",
  "frontend/components/layout",
  "frontend/components/dashboard",
  "frontend/components/leads",
  "frontend/components/pipeline",
  "frontend/components/analytics",
  "frontend/components/forms",
  "frontend/components/ai",
  "frontend/services",
  "frontend/hooks",
  "frontend/types",
  "frontend/lib",
  "frontend/public"
)

foreach ($directory in $directories) {
  New-Item -ItemType Directory -Force -Path $directory | Out-Null
}

